version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"

  app:
    image: hashicorp/http-echo
    command:
      - "-text=DevOps Homelab Working"
      - "-listen=:5678"
    ports:
      - "5678:5678"
