- name: Update apt cache
  apt:
    update_cache: yes
  become: true

- name: Fix broken packages
  shell: apt --fix-broken install -y
  ignore_errors: yes
  become: true

- name: Install Docker
  apt:
    name:
      - docker.io
      - docker-compose-v2
    state: present
  become: true

- name: Enable Docker
  service:
    name: docker
    enabled: yes
    state: started
  become: true
