name: Homelab Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Run Ansible Ping
        run: |
          cd ansible
          ansible all -m ping
