name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run docker playbook
        run: |
          cd ansible
          ansible-playbook -i inventory/hosts.ini playbooks/docker.yml

      - name: Run nginx playbook
        run: |
          cd ansible
          ansible-playbook -i inventory/hosts.ini playbooks/nginx.yml
